version: '3.9'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blooddonor-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/blooddonor
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: ${JWT_SECRET:-BloodConnectSuperSecretKeyForJWTSigningMustBe256BitsLong!!}
      MAIL_USERNAME: ${MAIL_USERNAME:-your@gmail.com}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-yourpassword}
      APP_FRONTEND_URL: ${APP_FRONTEND_URL:-http://localhost:5173}
      FIREBASE_CREDENTIALS: /app/resources/firebase-service-account.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./backend/src/main/resources/firebase-service-account.json:/app/resources/firebase-service-account.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blooddonor-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
